event_scheduler/config/routes.rb
Rails.application.routes.draw do
  # resources :users do
  #   resources :events
  # end

root "users#welcome"

get "user/signup" => "users#new", as: :signup

post "/users" => "users#create", as: :user_create

get "/user/:id" => "users#show", as: :show_user

get "/user/:id/edit" => "users#edit", as: :edit_user

patch "user/:id" => "users#update", as: :update_user

get "events/invitations" => "events#invitation", as: :user_invitation
# *********************************************************


  get '/login' => 'sessions#new', as: :login

  post '/login' => 'sessions#create', as: :session_create

  delete '/logout' => 'sessions#destroy', as: :session_destroy

# ****************************************************

get "/events" => "events#index", as: :list_events

get "/events/new" => "events#new", as: :new_event

post "/events" => "events#create", as: :create_event

get "/events/:event_id/edit" => "events#edit", as: :edit_event

patch "/events/:event_id" => "events#update", as: :update_event

delete "/events/:id" => "events#destroy" , as: :delete_event


# resources :sessions
# *********************************************************************************


  get '/sample' => 'events#sample', as: :sample

#  Prefix Verb   URI Pattern                               Controller#Action
#     user_events GET    /users/:user_id/events(.:format)          events#index
                # POST   /users/:user_id/events(.:format)          events#create
 # new_user_event GET    /users/:user_id/events/new(.:format)      events#new
# edit_user_event GET    /users/:user_id/events/:id/edit(.:format) events#edit
#      user_event GET    /users/:user_id/events/:id(.:format)      events#show
                # PATCH  /users/:user_id/events/:id(.:format)      events#update
#                 PUT    /users/:user_id/events/:id(.:format)      events#update
                # DELETE /users/:user_id/events/:id(.:format)      events#destroy
#           users GET    /users(.:format)                          users#index
#                 POST   /users(.:format)                          users#create
       # new_user GET    /users/new(.:format)                      users#new
#       edit_user GET    /users/:id/edit(.:format)                 users#edit
           # user GET    /users/:id(.:format)                      users#show
#                 PATCH  /users/:id(.:format)                      users#update
#                 PUT    /users/:id(.:format)                      users#update
#                 DELETE /users/:id(.:format)                      users#destroy


#  Prefix Verb   URI Pattern                  Controller#Action
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PATCH  /sessions/:id(.:format)      sessions#update
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy

end

event_scheduler/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :owner, class_name: "User"

	has_many :participents, dependent: :destroy
	has_many :users, through: :participents
end

event_scheduler/app/models/participent.rb
class Participent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

event_scheduler/app/models/user.rb
class User < ActiveRecord::Base

	
	has_many :events, foreign_key: :owner_id
	has_many :participents
	has_secure_password



		PASSWORD_FORMAT = /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/
	validates :firstname,  presence: true
	validates :lastname,  presence: true
	validates :email,  presence: { message: "must be given please" }
	validates_uniqueness_of :email

validates :password,  presence: { message: "must be given please" },   format: {with: PASSWORD_FORMAT},   confirmation: true,   on: :create 
end

event_scheduler/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  def current_user
    # binding.pry
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
  	!!current_user  	
  end

  def must_login
	if !logged_in?
		flash[:danger]="Please Login"
		redirect_to login_path
	end  	
  end
end

event_scheduler/app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :must_login, only: [:show, :edit, :new, :index, :create, :update, :destroy, :invitation]

	def new
		# binding.pry
		@users=User.all
	end

	def show
		
	end

	def index
		# binding.pry
		@events=Event.all
		@users=User.all
	end


	def create
		# binding.pry
		User.find(current_user).events << Event.new(event_params)
		# binding.pry
		if params["user_ids"]
		Event.last.users << User.find(params["user_ids"])
		end
		 redirect_to list_events_path
	end

	def edit
		@users=User.all
		@event=Event.find(params["event_id"])
		@current_event_user=@event.users
	end

	def update
		# binding.pry
		@event=Event.find(params["event_id"])
		@event.update(event_params)
		
		@event.users.clear

		if (params["user_ids"])
			@event.users << User.find(params["user_ids"])
		end
		@event.save

		redirect_to list_events_path
	end

	def destroy
		@event=Event.find(params[:id])
		@event.destroy
		redirect_to list_events_path
	end

	def invitation
		# binding.pry
		@a =[]
		current_user.participents.each do |p|
			@a << p.event_id
		end

		@events=Event.find(@a)

		respond_to do |format|
			format.html {redirect_to list_events_path}
			format.js
		end
	end
	


	
	


	private
	def event_params
		params.require(:event).permit(:title, :venue, :date, :time, :desc, :status )
	end
end

event_scheduler/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :must_login, only: [:show, :destroy]

  def new
  end

  def create
  	user = User.find_by(email: params[:login][:email] )

    
  	if user && user.authenticate(params[:login][:password])
      session[:user_id]=user.id
      flash[:success]="welcome #{current_user.firstname} #{current_user.lastname}  "
      redirect_to list_events_path(current_user)
  	else
      flash[:danger]="email or password is incorrect"
     # binding.pry
      redirect_to root_path
  	end
  end

  def destroy
     session[:user_id]=nil
     flash[:success]="Logged out! "
     redirect_to root_path
  end
end

event_scheduler/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :must_login, only: [:show, :edit, :update]

	def welcome
		
	end

	def new
		@user=User.new
	end

	def show
		
	end

	def edit
		@user =User.find(params[:id])
	end

	def create

		@user=User.new(user_params)
		if @user.save
			flash[:success]="User created successfully"
			redirect_to login_path
		else
			# flash[:danger]="Failed to create the user try again"
			
			redirect_to root_path
		end
		
	end

	def update
		@user =User.find(params[:id])
		if @user.update(user_params)
		flash[:success]="User updated successfully"
		redirect_to show_user_path
	else
			flash[:danger]="Failed to update user"

			render 'edit'
	end
	end

	private
	def user_params
		params.require(:user).permit(:firstname, :lastname, :username, :email, :phone, :password, :password_confirmation)
	end
end

event_scheduler/app/helpers/application_helper.rb
module ApplicationHelper
end

event_scheduler/app/helpers/events_helper.rb
module EventsHelper
end

event_scheduler/app/helpers/sessions_helper.rb
module SessionsHelper
end

event_scheduler/app/helpers/users_helper.rb
module UsersHelper
end

event_scheduler/app/views/events/_invitation.html.erb
<div class="container">
 
  <!-- Trigger the modal with a button -->
  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->

  <!-- Modal -->
  <div class="modal fade" id="invitation-modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Invited events</h4>
        </div>
        <div class="modal-body">


      <% @events.each do |e|%>
            <div class="well">
              <strong>Event Name :</strong> <%= e.title%><br>
              <strong>Venue :</strong> <%= e.venue%><br>
              <strong>Date :</strong> <%= e.date%><br>
              <strong>Time :</strong> <%= e.time%><br>
            </div>
      <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

event_scheduler/app/views/events/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3 well">

<% if current_user.id == Event.find(params["event_id"]).owner_id%>
<h3><b>Edit Event</b></h3>
<hr>
<%= form_for :event, url: update_event_path(@event), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, "class" => "form-control", "required" => "true" %>
  </p>
 
  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue, "class" => "form-control" , "required" => "true" %>
  </p>

  <p>
    <%= f.label :date %><br>
  <%= f.text_field :date, :id=>"datepicker", "class" => "form-control",  :required => "true" %>
  </p>
  <p>
    <%= f.label :time %><br>
   <%= f.time_field :time , "class" => "form-control", "required" => "true"%>
  </p>
  <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc, "class" => "form-control" , "required" => "true" %>
  </p>

  <p>
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select([['open',nil],['close',false]]) , "required" => "true" %>
  </p> 

<hr>
<%= f.fields_for :partcipent  do |ff| %>
<h3><b>Add participents</b></h3>
<hr>
<% @users.each do |t| %>
  <%if !(t.id==current_user.id)%>
  <%= check_box_tag "user_ids[]", t.id , @event.user_ids.include?(t.id)   %>
  <%=  t.firstname %>&nbsp; <%=  t.lastname %><br>

  <% end %>
  
<% end %>
<% end %>

<br>
<p>
	<%= f.submit "Update event" , "class" => "btn btn-primary " %>
  <%= link_to "Cancel", list_events_path, "class" => "btn btn-default" %>
</p>
<% end %>




<!-- ************************************************************************ -->
<% else %>
<h1> Event details</h1>
<%= form_for :event, url: update_event_path(@event), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, "class" => "form-control", "required" => "true", "disabled"=>"true"%>
  </p>
 
  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue, "class" => "form-control" , "required" => "true", "disabled"=>"true" %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date, "class" => "form-control" , "required" => "true", "id" => "datepicker", "disabled"=>"true" %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_field :time, "class" => "form-control" , "required" => "true" , "id" => "timepicker", "disabled"=>"true"%>
  </p>
  <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc, "class" => "form-control" , "required" => "true", "disabled"=>"true" %>
  </p>

 


<%= f.fields_for :partcipent  do |ff| %>
<h1>List of Participents</h1>
<% @current_event_user.each do |t| %>
 <ul>
  <li><%=  t.firstname.upcase %>&nbsp; <%=  t.lastname.upcase %><br></li>
</ul>
  <% end %>
  

<% end %>

<br>
<p>
  <%= f.submit "update event", "disabled"=>"true" %>
</p>
<% end %>
<% end %>
</div></div></div>

event_scheduler/app/views/events/index.html.erb
<div class="addeventdiv">
  
 <button type="button" class = "addevent btn btn-primary"  data-toggle="modal" data-target="#myModal">Create new event</button>
</div>

<div class="container">


		
	<% @events.each do |e| %>

<div class="row">
<div class="col-md-6 well">



	<strong>Event : </strong><%= link_to e.title.capitalize, edit_event_path(e) %><br>
	<strong>Organiser : </strong>	<%= User.find(e.owner_id).firstname%>&nbsp;<%= User.find(e.owner_id).lastname%><br>
  
  <a href="#" data-toggle="modal" data-target="#myModal-<%= e.id%>">Participants</a><br><br>

 <div class="status">
  <% if e.status== nil %>
  <div>
    <span class="green-back white-color">open</span> 
  </div> 

  <%elsif e.status== false %>
   <div>
    <span class="red-back white-color">close</span> 
  </div>   
<% end %>
  </div>
  <% if current_user.id== e.owner_id%>
  <%= link_to 'Delete event', delete_event_path(e), method: :delete, data: { confirm: 'Are you sure?' } ,"class" => "btn btn-primary"  %>
  <% end %>
<!-- ///////////////////////////Participants //////////////////////////////// -->
	
<div class="container">
 

 
  <!-- Modal -->
  <div class="modal fade" id="myModal-<%= e.id%>" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Event : <%= e.title  %> </h4>
        </div>
        <div class="modal-body">
       
          <table class="table">
          <tr>  <th>List of Participants</th></tr>
          	<% e.users.each do |u| %>
    
          	<tr>
           
          		<td><%= u.firstname%>&nbsp;<%= u.lastname%></td>
          	</tr>
			       <% end %>

          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>



<!-- ///////////////////////////////////////////////////////////////// -->

		

</div>


<div class="col-md-6">

	
		
    <div class="well">
    
<div class="form-group">
  
<div class="row">
  <div class="col-md-3">
		<strong>Event Name : </strong>
</div>
 <div class="col-md-9">

    <p class="well well-sm" ><%= e.title %></p>
</div>
</div>

<div class="row">
  <div class="col-md-3">
    <strong>Venu : </strong>
</div>
 <div class="col-md-9">

    <p class="well well-sm" ><%= e.venue %></p>
</div>
</div>

<div class="row">
  <div class="col-md-3">
    <strong>Date : </strong>
</div>
 <div class="col-md-9">

    <p class="well well-sm" ><%= e.date %></p>
</div>
</div>

<div class="row">
  <div class="col-md-3">
    <strong>Time : </strong>
</div>
 <div class="col-md-9">

    <p class="well well-sm" ><%= e.time %></p>
</div>
</div>

<div class="row">
  <div class="col-md-3">
    <strong>Description : </strong>
</div>
 <div class="col-md-9">

    <p class="well well-sm" ><%= e.desc %></p>
</div>
</div>


       


  

  </div>
		</div >
		
			
</div>
</div><!-- row -->
<% end %>

</div><!-- container -->



<!-- ********************************Create event****************************************** -->

 <%= render "partials/create_event" %>

 <div id="modal-place"> </div>

event_scheduler/app/views/events/invitation.js.erb
$("#modal-place").after("<%= j render('invitation')%>");
$("#invitation-modal").modal('show');

event_scheduler/app/views/events/list_participents.html.erb
<h1>List of participents</h1>

<% User.find(params["user_id"]).events.find_by_id(params["event_id"]).participents.each do |p|%>
<%= User.find(p.user_id).firstname %>&nbsp;<%= User.find(p.user_id).lastname %>

	<% end %>

<div class="jumbotron"></div>

event_scheduler/app/views/events/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3 well">
<h1 class="createevent-title">Create Event</h1>
<%= form_for :event, url: create_event_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, "class" => "form-control" %>
  </p>
 
  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue, "class" => "form-control" %>
  </p>

  <p>
    <%= f.label :date %><br>
   <%= f.text_field :name, :id=>"datepicker", :readonly=>"true" %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_select :time, "class" => "form-control"%>
  </p>
  <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc, "class" => "form-control" %>
  </p> 


<%= f.fields_for :partcipent  do |f| %>
<h1 class="createevent-title">Add participents</h1>
<% @users.each do |t| %>
  <%if !(t.id==current_user.id)%>
  <%= check_box_tag "user_ids[]", t.id  %>
  <%=  t.firstname %>&nbsp; <%=  t.lastname %><br>

  <% end %>
  
<% end %>

<% end %>





  <p><br>
    <%= f.submit 'add participent', "class"=>"btn btn-primary" %>
  </p>
<% end %>

</div>
</div>
</div>

event_scheduler/app/views/partials/_create_event.html.erb
<div class="container">
  

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><b>Create New Event</b></h4>
        </div>
        <div class="modal-body">
          

  

<%= form_for :event, url: create_event_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, "class" => "form-control" , "required" => "true"%>
  </p>
 
  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue, "class" => "form-control" , "required" => "true"%>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, :id=>"datepicker", "class" => "form-control", :readonly=>"true", :required => "true" %>
  </p>
  <p>
    <%= f.label :time %><br>
    <%= f.time_field :time , "class" => "form-control", "required" => "true"%>
  </p>
  <p>
    <%= f.label :desc %><br>
    <%= f.text_area :desc, "class" => "form-control" , "required" => "true"%>
  </p> 

<hr>
<%= f.fields_for :partcipent  do |f| %>
<h4 ><b>Select participants</b></h4><br>
<% @users.each do |t| %>
  <%if !(t.id==current_user.id)%>
  <%= check_box_tag "user_ids[]", t.id  %>
  <%=  t.firstname %>&nbsp; <%=  t.lastname %><br>

  <% end %>
  
<% end %>

<% end %>





  
   



  



        </div>
        <div class="modal-footer">
         <%= f.submit 'Create Event', "class"=>"btn btn-primary" %>
  

          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

event_scheduler/app/views/partials/_login.html.erb
<div class="container">
 
  
  
  <!-- Modal -->
  <div class="modal fade " id="myModal-login" role="dialog">
    <div class="modal-dialog ">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title login-title "><b>Login</b></h4>
        </div>
        <div class="modal-body">
          
  
  
  <%= form_for :login, :html => {:id => "loginform"}, url: session_create_path do |f| %>
    <div class="form_group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' , "required"=>"true" %>
    </div>
    <div class="form_group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control', "required"=>"true"  %>
    </div><br>

   



        </div>
        <div class="modal-footer">
         <%= f.submit 'Login', class: 'btn btn-primary'  %>
  
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button><br>
         
          <% end %>

        </div>
        <div class="twitter">
          
         <a href="#" >Login with twitter</a>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

event_scheduler/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
      <a class="navbar-brand" href="#">Event Scheduler</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
     
      <ul class="nav navbar-nav navbar-right">
        
      <% if !logged_in? %>
        <li class="signup"><a href="#"  data-toggle="modal" data-target="#myModal-signup">Sign Up</a></li>
        <li class="login"><a href="#" data-toggle="modal" data-target="#myModal-login">Login</a></li>
        
    
      <% elsif logged_in? %>
      <li><%= image_tag("avatar.jpg", size: "60x60", alt: "profile ing", "class" => "img-circle")%></li>
      <li> 
  <%= link_to User.find(current_user.id).firstname.upcase+" "+User.find(current_user.id).lastname.upcase,show_user_path(current_user) %></li>
  <li class="logout"><%= link_to "invitations", user_invitation_path, remote: true  %></li>
        <li class="logout"><%= link_to 'Logout', session_destroy_path, method: :delete %></li>
     <% end %>
     
      </ul>
    </div>
  </div>
</nav>

event_scheduler/app/views/partials/_signup.html.erb
<div class="container">

  <!-- Modal -->
  <div class="modal fade" id="myModal-signup" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><b>Sign Up</b></h4>
        </div>
        <div class="modal-body">
      
<%= form_for :user, url: user_create_path, :html => {:id => "signupform"} do |f| %>


<% if @user %>


             <% if @user.errors.any? %>
                <div id="error_explanation">
                  <h2>

                    <%= pluralize(@user.errors.count, "error") %> prohibited
                    this article from being saved:
                  </h2>
                  <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                      <li><% flash[:danger]= msg %></li>

                      <% binding.pry %>
                    <% end %>
                  </ul>
                </div>
              <% end %>
               <% end %>


            
         

  
  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname, "class" => "form-control firstname", "required" => "true"%>
  </p>
 
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname, "class" => "form-control lastname", "required" => "true" %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, "class" => "form-control username", "required" => "true" %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email,  "class" => "form-control email", "required" => "true"  %><p id="email-error"></p>
  </p>
  <p>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone, "class" => "form-control mobile", "required" => "true" %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, "class" => "form-control password", "required" => "true" %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, "class" => "form-control password-confirm", "required" => "true" %>
  </p>
 
  




        </div>
        <div class="modal-footer">
       
    <%= f.submit "Register User", "class"=>"btn btn-primary" %>
 

          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

event_scheduler/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for :user, url: update_user_path(@user), method: :patch do |f| %>
  <p>
    <%= f.label :FirstName %><br>
    <%= f.text_field :firstname, "class" => "form-control", "required" => "true" %>
  </p>
 
  <p>
    <%= f.label :LastName %><br>
    <%= f.text_field :lastname, "class" => "form-control" , "required" => "true" %>
  </p>

<p>
    <%= f.label :UserName %><br>
    <%= f.text_field :username, "class" => "form-control" , "required" => "true" %>
  </p>
 <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email, "class" => "form-control" , "required" => "true", "disabled"=>"true" %>
  </p>


<p>
  <%= f.submit "Update user" , "class" => "btn btn-primary " %>
 
</p>
<% end %>
    </div>
  </div>
</div>

event_scheduler/app/views/users/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3 well">
<h1 class="register"> Sign Up</h1>
<%= form_for :user, url: user_create_path, :html => {:id => "signupform"} do |f| %>

    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
      
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%=flash[:danger]= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname, "class" => "form-control firstname", "required" => "true"%>
  </p>
 
  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname, "class" => "form-control lastname", "required" => "true" %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, "class" => "form-control username", "required" => "true" %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email,  "class" => "form-control email", "required" => "true"  %><p id="email-error"></p>
  </p>
  <p>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone, "class" => "form-control mobile", "required" => "true" %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, "class" => "form-control password", "required" => "true" %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, "class" => "form-control password-confirm", "required" => "true" %>
  </p>
 
  <p>
    <%= f.submit "Register User" %>
  </p>
<% end %>

</div>
</div>
</div>

event_scheduler/app/views/users/show.html.erb
<div class="container">
	<div class="row">
		

		<div class="col-md-6 col-md-offset-3 well jumbotron">
<h1>User Details</h1>

<div class="row">
<div class="col-md-6 name">
	<strong>Name : </strong>	
	
</div>
<div class="col-md-6 value">
	 <%= current_user.firstname.upcase %>&nbsp;
	<%= current_user.lastname.upcase %>
</div>
</div>

<div class="row">
<div class="col-md-6 name">
	<strong>Email : </strong>
	
</div>
<div class="col-md-6 value">
		 <%= current_user.email %><br>
</div>
</div>


<div class="row">
<div class="col-md-6 name">
<strong>Use Name : </strong>
	
</div>
<div class="col-md-6 value">
<%= current_user.username %><br>
</div>
</div>

	

</div>




	</div>
</div>



<div class="user-edit">
	
<%= link_to '<< BACK',list_events_path(current_user)%>
|
<%= link_to 'EDIT >>',edit_user_path(current_user)%>
</div>